name: Staging

on:
  push:
    branches: [release/*]
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-staging

jobs:
  axum-api:
    uses: ./.github/workflows/axum-api.yml

  svelte-ui:
    uses: ./.github/workflows/svelte-ui.yml

  build:
    needs:
      - axum-api
      - svelte-ui
    runs-on: ubuntu-22.04

    environment: staging

    permissions:
      # For pushing to GHCR
      packages: write

    steps:
      - uses: actions/checkout@v4
      # Download build artifacts
      - uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: type=semver,pattern={{version}}
      - run: echo ${{ steps.meta.outputs.tags }}

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker-infra/Dockerfile
          load: true
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

          # Log in to GHCR again to ensure authentication for inspection of private images
      - name: Inspect
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin
          docker image inspect ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
